export enum AuthError {
    EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
    TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
    INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
    TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
    WORKSPACE_CREATE_FAILED = 'AUTH_WORKSPACE_CREATE_FAILED',
    REGISTER_FAILED = 'AUTH_REGISTER_FAILED',
}
