# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x06parser\"E\n\x0cParseRequest\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\x12\r\n\x05tasks\x18\x02 \x03(\t\x12\x14\n\x0cprofile_json\x18\x03 \x01(\t\"$\n\rParseResponse\x12\x13\n\x0b\x62locks_json\x18\x01 \x01(\t2E\n\rParserService\x12\x34\n\x05Parse\x12\x14.parser.ParseRequest\x1a\x15.parser.ParseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEREQUEST']._serialized_start=24
  _globals['_PARSEREQUEST']._serialized_end=93
  _globals['_PARSERESPONSE']._serialized_start=95
  _globals['_PARSERESPONSE']._serialized_end=131
  _globals['_PARSERSERVICE']._serialized_start=133
  _globals['_PARSERSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
